### ISSUE TITLE
ARM64 Image Support

### ISSUE THREAD

**Issue by andrewrust13** [grafana/flagger-k6-webhook#128]
Hi,

Would it be possible to create an ARM64 based image to go alongside the existing AMD64 image.

We currently use the AMD image but are looking to switch over to using AWS EC2 Graviton nodes on our EKS cluster and would need an ARM compatible image.

Thanks.

**Comment by zerok** [comment]
Hi 🙂

`latest` should now support linux/amd64 and linux/arm64. Can you please give it a try?

**Comment by zerok** [comment]
Awesome 😄 Glad I could help 😄
